[phases.setup]
nixPkgs = ['python311', 'postgresql', 'redis', 'rabbitmq-server']

[phases.install]
cmds = ['python3 -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "./start.sh"
