[phases.setup]
nixPkgs = ['python311', 'pip', 'postgresql', 'redis', 'rabbitmq-server']
aptPkgs = ['build-essential', 'libpq-dev']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "./start.sh"
