[phases.setup]
nixPkgs = ['python311', 'git', 'redis']
aptPkgs = ['build-essential', 'libpq-dev']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "./start.sh"
