# Generated by Django 5.1.1 on 2024-09-30 09:33

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.datetime(
                                    2024,
                                    9,
                                    29,
                                    9,
                                    33,
                                    21,
                                    974153,
                                    tzinfo=datetime.timezone.utc,
                                )
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.datetime(
                                    2024,
                                    9,
                                    30,
                                    9,
                                    34,
                                    21,
                                    974153,
                                    tzinfo=datetime.timezone.utc,
                                )
                            ),
                        ]
                    ),
                ),
                ("value", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.charttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
    ]
