# Generated by Django 5.1.1 on 2024-11-09 20:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualcontrol",
            name="time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2024,
                            11,
                            8,
                            20,
                            26,
                            18,
                            842353,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime(
                            2024,
                            11,
                            9,
                            20,
                            27,
                            18,
                            842353,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ]
            ),
        ),
    ]
