# Generated by Django 5.1.1 on 2024-10-02 15:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_manualcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="duration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 2, 15, 23, 42, 305657, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="manualcontrol",
            name="time",
            field=models.DateTimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.datetime(
                            2024,
                            10,
                            1,
                            15,
                            23,
                            42,
                            305657,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.datetime(
                            2024,
                            10,
                            2,
                            15,
                            24,
                            42,
                            305657,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ]
            ),
        ),
    ]
