# Generated by Django 5.1.1 on 2025-01-22 20:49

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_manualcontrol_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='timeframe',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manualcontrol',
            name='time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2025, 1, 21, 20, 49, 51, 525949, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2025, 1, 22, 20, 50, 51, 525960, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.CreateModel(
            name='PriceStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.charttype')),
            ],
        ),
    ]
